### ISSUE TITLE
Lein droid fails on Windows 10

### ISSUE THREAD

**Issue by Ifiht** [clojure-android/lein-droid#155] opened 2016-09-15 04:20 UTC
When passing arguments to droid, it fails with the following:
```
Retrieving droid/lein-template/0.1.8/lein-template-0.1.8.pom from clojars
Retrieving droid/lein-template/0.1.8/lein-template-0.1.8.jar from clojars
java.lang.IllegalArgumentException: No value supplied for key: true
 at clojure.lang.PersistentHashMap.create (PersistentHashMap.java:77)
    clojure.core$hash_map.invokeStatic (core.clj:387)
    [...]
    clojure.main.main (main.java:37)
```
the result is the same for any command attempting to create a project with more than the default:
```
lein new droid appname
lein new droid appname dom.mydom.appname
```
At first I thought this was my path, so I went through the heinous process of renaming my home folder in windows, it now has no spaces or special characters. Here's the system specs:
```
> systeminfo
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.14393 N/A Build 14393
> java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
> lein -v
Leiningen 2.7.0 on Java 1.7.0_79 Java HotSpot(TM) 64-Bit Server VM
```
Any help would be awesome, just getting started in this stuff so obviously not a subject matter expert.

**Comment by neupsh** [comment] 2016-10-07 22:43
I am facing the same on arch linux with lein:
Leiningen 2.7.1 on Java 1.8.0_92 Java HotSpot(TM) 64-Bit Server VM
lein-droid verson: 0.4.4

**Comment by jitendranair** [comment] 2016-10-15 06:19
Facing the same issue, I am on Ubuntu 16.04:

$ lein --version
Leiningen 2.7.1 on Java 1.7.0_80 Java HotSpot(TM) 64-Bit Server VM

$ cat ~/.lein/profiles.clj
{:user {:plugins [[lein-droid "0.4.4"]]}}

**Comment by alexander-yakushev** [comment] 2016-10-23 09:32
This bug happened because Leinigen 2.7.0 broke their [internal, to be fair] function `get-dependencies`. I pushed a fix to the template, `lein new droid appname dom.mydom.appname` should be working now. Thanks for reporting! I will close the issue when somebody confirms it works for them.

#154 is also related.

**Comment by jitendranair** [comment] 2016-10-23 11:06
Done , the fix works : 

$ lein --version
(Warning: profile :android-common not found.)
(Warning: profile :android-user not found.)
Leiningen 2.7.1 on Java 1.8.0_91 OpenJDK 64-Bit Server VM


$ lein new droid test-bug-115 org.exmaple.testbug115
Using lein-droid 0.4.5
Resolving latest artifact versions...
Couldn't resolve the latest org.skummet/clojure version, using default 1.7.0-r1
Couldn't resolve the latest org.clojure-android/clojure version, using default 1.7.0-r3
Couldn't resolve the latest neko version, using default 4.0.0-alpha5
Creating project test-bug-115 ...

$ lein droid doall
----- snip ------
Creating APK...
Signing APK with /home/jitendran/.android/debug.keystore ...
Aligning APK...
Installing APK...
Launching APK...
Binding device port 9999 to local port 9999 ...


Thanks  Alex

**Comment by alexander-yakushev** [comment] 2016-10-23 11:46
@jitendranair Great! You might want to jump directly to `0.4.6` as it fixes another regression regarding AAR dependencies.

**Closed by alexander-yakushev** 2016-10-23 11:46 UTC
Labels: version-mismatch

**Comment by jitendranair** [comment] 2016-10-23 12:56
Seems 0.4.6 is  not available on  clojars.org

**Comment by alexander-yakushev** [comment] 2016-10-23 13:12
Sorry, my bad. Should be there now.
